name: black

on:
  push:
    branches: [ main, master, add-gpu ]
  pull_request:
    branches: [ main, master ]

jobs:
  format-check:
    name: Check Python formatting with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Run Black (check only)
        run: |
          black --check .
